export const openApiDescription = [
	"Keyzori creates, validates, meters, hardware-limits, and revokes software licenses. This page documents the complete HTTP API and every supported configuration setting.",
	"",
	"## License configuration",
	"",
	"Send these fields to `POST /admin/keys`. Only `userId` and `type` are always required.",
	"",
	"| Field | Default | Meaning |",
	"| --- | --- | --- |",
	"| `userId` | Required | ID returned by `POST /admin/users`. |",
	"| `type` | Required | `PERPETUAL`, `SUBSCRIPTION`, or `USAGE`. |",
	"| `limitIp` | `0` | Maximum distinct source IP addresses ever registered to the license. Zero is unlimited. |",
	"| `limitHwid` | `0` | Maximum distinct hardware IDs ever registered to the license. Zero is unlimited. |",
	"| `limitConcurrent` | `0` | Maximum active 45-second sessions. Zero is unlimited. The SDK refreshes its session with heartbeats. |",
	"| `limitUsage` | `0` | Required and greater than zero for `USAGE`. One unit is consumed for each new session, but not for heartbeats. |",
	"| `trialDurationMin` | `0` | Optional trial length for any license type. The timer begins at the first successful handshake. Zero disables the trial. |",
	"| `customFields` | `{}` | JSON returned to the licensed application after validation, such as plan or feature data. Do not store secrets here. |",
	"| `expiresAt` | `null` | Future ISO 8601 timestamp required for `SUBSCRIPTION` and rejected for other types. |",
	"",
	"`id`, `key`, `firstActivatedAt`, `revoked`, and `createdAt` are generated or managed by Keyzori and cannot be supplied during creation. The full `key` secret is returned only once. Explicit IP/HWID whitelist rows are enforced when present, but the current HTTP API and bundled CLI do not manage whitelist rows.",
	"",
	"### Complete license examples",
	"",
	"**Perpetual license for one device**",
	"",
	"```json",
	'{"userId":"OWNER_ID","type":"PERPETUAL","limitHwid":1,"limitConcurrent":1,"customFields":{"tier":"pro"}}',
	"```",
	"",
	"**Subscription expiring at a fixed time**",
	"",
	"```json",
	'{"userId":"OWNER_ID","type":"SUBSCRIPTION","limitHwid":2,"limitConcurrent":2,"expiresAt":"2027-01-01T00:00:00.000Z","customFields":{"plan":"annual"}}',
	"```",
	"",
	"**Usage license with 100 session admissions**",
	"",
	"```json",
	'{"userId":"OWNER_ID","type":"USAGE","limitUsage":100,"limitConcurrent":1,"customFields":{"credits":100}}',
	"```",
	"",
	"## Server environment configuration",
	"",
	"Set these on the `keyzori-server` process or container. Restart the server after changing them.",
	"",
	"| Variable | Required/default | Meaning |",
	"| --- | --- | --- |",
	"| `DATABASE_URL` | Required | PostgreSQL URL using `postgres://` or `postgresql://`. Used for licenses, owners, devices, and migrations. |",
	"| `REDIS_URL` | Required | Redis URL using `redis://` or `rediss://`. Used for sessions and rate limits. |",
	"| `ADMIN_API_KEY` | Required | Random administrator secret of at least 32 characters, sent as `X-Admin-Key`. Placeholder values are rejected. |",
	"| `ADMIN_API_KEYS` | Empty | Comma-separated previous administrator secrets accepted during zero-downtime rotation. Every value must meet the primary-key rules. |",
	"| `HOST` | `0.0.0.0` | Address or hostname on which the HTTP server listens. |",
	"| `PORT` | `3000` | HTTP port from 1 through 65535. The container health check uses the same value. |",
	"| `TRUST_PROXY_HEADERS` | `false` | Enables forwarded client-IP headers. Enable only when direct access is blocked by a trusted proxy. |",
	"| `TRUSTED_PROXY_CIDRS` | Required when proxy trust is enabled | Comma-separated immediate-proxy IPv4/IPv6 CIDRs allowed to supply forwarded addresses. |",
	"| `OPENAPI_ENABLED` | `true` | Set to `false` to disable this Scalar UI and `/docs/openapi.json`. |",
	"| `RATE_LIMIT_PER_MINUTE` | `60` | Per-source-IP request budget for license and administrator routes; accepted range is 1 through 100000. Probes are excluded. |",
	"| `MAX_REQUEST_BODY_BYTES` | `65536` | Maximum JSON request body size; accepted range is 1024 through 10485760 bytes. |",
	"| `DRIZZLE_MIGRATIONS_PATH` | Auto-detected | Optional migration-directory override for nonstandard binary layouts. |",
	"",
	"## TypeScript SDK configuration",
	"",
	"These options are passed to `new LicenseClient(...)` in the official `@keyzori/sdk` package.",
	"",
	"| Option | Required/default | Meaning |",
	"| --- | --- | --- |",
	"| `apiKey` | Required | Full license secret returned once by Keyzori. |",
	"| `serverUrl` | Required | Keyzori base URL. HTTPS is required except for loopback development. |",
	"| `heartbeatIntervalMs` | `30000` | Delay after each completed heartbeat before the next heartbeat. |",
	"| `maxRetries` | `2` | Consecutive heartbeat failures allowed before the client stops. |",
	"| `requestTimeoutMs` | `10000` | Timeout for each handshake or logout request. |",
	"| `logLevel` | `none` | `none`, `error`, `warn`, `info`, or `debug`. |",
	"",
	"Start with `POST /admin/users`, then `POST /admin/keys`. Licensed applications use `POST /v1/handshake` and `POST /v1/logout` directly or through the SDK.",
].join("\n");
